database:
 db-host: "localhost"
 db-name: "minecraft"
 db-port: "3306"
 db-username: "root"
 db-password: ""

configuration:
 create-logs-every: "1200"

messages:
 no-logs-found: " §cNon sono stati trovati logs per questo player."
 wrong-command-use: " §cUso scorretto del comando!"
 log-created: " §a Hai creato con successo un log dell'inventario di questo giocatore!"
 logs-cleared: " §aHai pulito con successo §7%logs_number%§a logs!"
 no-permissions: " §cNon hai i permessi per usare qeusto comando!"
